django/rially/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from rially import settings
from rially.views import LocationView, LoginView, HomeView, LogoutView, \
    ScoreView, AdminScoreView, BonusView, TasksView, AdminRateView, \
    AdminDownloadView, AdminTaskRateView, HelpView, AdminPanelView, \
    AdminDistributedRateView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^home/$', HomeView.as_view()),
    url(r'^tasks/$', TasksView.as_view()),
    url(r'^bonus/$', BonusView.as_view()),
    url(r'^score/$', ScoreView.as_view()),
    url(r'^adminpanel/$', AdminPanelView.as_view()),
    url(r'^adminscore/$', AdminScoreView.as_view()),
    url(r'^adminrate/$', AdminRateView.as_view()),
    url(r'^admintaskrate/$', AdminTaskRateView.as_view()),
    url(r'^adminratedist$', AdminDistributedRateView.as_view()),
    url(r'^admindownload/$', AdminDownloadView.as_view()),
    url(r'^location/(?P<pk>\d+)/', LocationView.as_view()),
    url(r'^help/$', HelpView.as_view()),
    url(r'^$', RedirectView.as_view(url='/home')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/rially/models.py
from functools import partial

import os

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.crypto import get_random_string
from django.db.models import Sum
from django.db.models import CASCADE


def _update_filename(instance, filename, path):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(get_random_string(32), ext)
    return os.path.join(path, filename)


def upload_to(path):
    return partial(_update_filename, path=path)


class Team(models.Model):
    name = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    telegram_token = models.CharField(max_length=50, default=None, null=True)

    def solved_tasks(self):
        return self.tasksolve_set.filter(team=self).values_list('task__id', flat=True).all()

    def processing_tasks(self):
        return self.submitted_set.filter(content_type=ContentType.objects.get(model='task')).values_list('object_id', flat=True).all()

    def solved_locationtasks(self):
        return self.locationtasksolve_set.filter(team=self).values_list('task__id', flat=True).all()

    def processing_locationtasks(self):
        return self.submitted_set.filter(content_type=ContentType.objects.get(model='locationtask')).values_list('object_id', flat=True).all()

    def points_tasks(self):
        res = self.solved_tasks().aggregate(Sum('points'))['points__sum']
        res2 = self.solved_locationtasks().aggregate(Sum('points'))['points__sum']
        if res is None:
            res = 0
        if res2 is None:
            res2 = 0
        return res + res2

    def solved_pictures(self):
        return self.picturesolve_set.filter(team=self).values_list('picture', flat=True).all()

    def processing_pictures(self):
        return self.submitted_set.filter(content_type=ContentType.objects.get(model='picture')).values_list('object_id', flat=True).all()

    def points_pictures(self):
        res = self.solved_pictures().aggregate(Sum('picture__points'))['picture__points__sum']
        if res is None:
            res = 0
        return res

    def solved_locations(self):
        return self.locationsolve_set.filter(team=self).values_list('location', flat=True).all()

    def processing_locations(self):
        return self.submitted_set.filter(content_type=ContentType.objects.get(model='location')).values_list('object_id', flat=True).all()

    def points_bonus(self):
        res = self.bonus_set.aggregate(Sum('points'))['points__sum']
        if res is None:
            res = 0
        return res

    def points_penalty(self):
        res = self.penalty_set.aggregate(Sum('points'))['points__sum']
        if res is None:
            res = 0
        else:
            res *= -1
        return res

    def points_total(self):
        return self.points_pictures() + self.points_tasks() + self.points_bonus() + self.points_penalty()

    def __str__(self):
        return 'Team: %s' % self.name


class TeamTelegramSession(models.Model):
    telegram_chat_id = models.CharField(max_length=64, primary_key=True)
    team = models.ForeignKey(Team, on_delete=CASCADE)


class Submitted(models.Model):
    object_id = models.PositiveIntegerField()
    type = GenericForeignKey('content_type', 'object_id')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    file = models.CharField(max_length=64)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    received = models.DateTimeField(auto_now_add=True)


class PriorityQueueItem(models.Model):
    submitted = models.ForeignKey(Submitted, on_delete=models.CASCADE)
    time_sent = models.DateTimeField()

    def __str__(self):
        return 'PrioQueue Item %s for %s' % (self.submitted.object_id, self.submitted.team)

class QueueItem(models.Model):
    submitted = models.ForeignKey(Submitted, on_delete=models.CASCADE)
    time_sent = models.DateTimeField()

    def __str__(self):
        return 'Queue Item %s for %s' % (self.submitted.object_id, self.submitted.team)


class Location(models.Model):
    name = models.TextField()
    description = models.TextField()
    id = models.IntegerField(unique=True, primary_key=True)
    ordering = ['id']

    def __str__(self):
        return 'Location %s: %s' % (self.id, self.name)


class Puzzle(models.Model):
    name = models.TextField()
    file = models.FileField(upload_to=upload_to(''), null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=CASCADE)

    def __str__(self):
        return 'Puzzle %s (%s): %s' % (self.id, self.location, self.name)


class LocationTask(models.Model):
    name = models.TextField()
    location = models.ForeignKey(Location, on_delete=CASCADE)

    def __str__(self):
        return 'LocationTask %s (%s): %s' % (self.id, self.location, self.name)


class Task(models.Model):
    name = models.TextField()

    def __str__(self):
        return 'Task %s: %s' % (self.id, self.name)


class Picture(models.Model):
    points = models.IntegerField()
    image = models.ImageField(upload_to=upload_to(''))
    location = models.ForeignKey(Location, on_delete=CASCADE)

    def __str__(self):
        return 'Picture (%s): %s' % (self.location, self.id)


class PictureSolve(models.Model):
    picture = models.ForeignKey(Picture, on_delete=CASCADE)
    team = models.ForeignKey(Team, on_delete=CASCADE)
    content = models.CharField(max_length=50)

    class Meta:
        unique_together = (("picture", "team"),)

    def __str__(self):
        return '%s solved %s' % (self.team, self.picture)


class LocationTaskSolve(models.Model):
    task = models.ForeignKey(LocationTask, on_delete=CASCADE)
    points = models.IntegerField()
    team = models.ForeignKey(Team, on_delete=CASCADE)
    content = models.CharField(max_length=50)

    class Meta:
        unique_together = (("task", "team"),)

    def __str__(self):
        return '%s solved %s' % (self.team, self.task)


class TaskSolve(models.Model):
    task = models.ForeignKey(Task, on_delete=CASCADE)
    points = models.IntegerField()
    team = models.ForeignKey(Team, on_delete=CASCADE)
    content = models.CharField(max_length=50)

    class Meta:
        unique_together = (("task", "team"),)

    def __str__(self):
        return '%s solved %s' % (self.team, self.task)


class LocationSolve(models.Model):
    location = models.ForeignKey(Location, on_delete=CASCADE)
    team = models.ForeignKey(Team, on_delete=CASCADE)
    content = models.CharField(max_length=50)

    class Meta:
        unique_together = (("location", "team"),)

    def __str__(self):
        return '%s unlocked %s' % (self.team, self.location)


class Aftermovie(models.Model):
    media = models.CharField(max_length=50)


class Bonus(models.Model):
    reason = models.TextField()
    points = models.IntegerField()
    team = models.ForeignKey(Team, on_delete=CASCADE)

    class Meta:
        verbose_name_plural = "Bonuses"

    def __str__(self):
        return '%s got a bonus of %s because %s' % (self.team, self.points, self.reason)


class Penalty(models.Model):
    reason = models.TextField()
    points = models.IntegerField()
    team = models.ForeignKey(Team, on_delete=CASCADE)

    class Meta:
        verbose_name_plural = "Penalties"

    def __str__(self):
        return '%s got a penalty of %s because %s' % (self.team, self.points, self.reason)

class SiteState(models.Model):
    submission_open = models.BooleanField()
    show_scoreboard = models.BooleanField()

    def save(self, *args, **kwargs):
        if self.id != None and SiteState.objects.all().count() > 1 or self.id == None and SiteState.objects.all().count() >= 1:
            raise ValueError("There can only be one SiteState entry.")
        else:
            super(SiteState, self).save(*args, **kwargs)

    def __str__(self):
        return  'Submissons are %s, ' % ("open" if self.submission_open else "closed") + \
                'Scores are %s.' % ("shown" if self.show_scoreboard else "hidden")

django/templates/admindownload.html
{% extends 'main.html' %}
{% load static %}
{% block pagebody %}
    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            <h1 class="header center orange-text">Aftermovie download</h1>
            <p class="center">{{ downloads|length }} items in aftermovie list. <a href="?download=zip"><i class="material-icons">file_download</i> Download zip</a></p>
        </div>
    </div>
    <ul class="collection">
        {% for d in downloads %}
            <li class="collection-item"><div>{{ d.media }}<a href="/media/{{ d.media }}" class="secondary-content"><i class="material-icons">file_download</i></a></div></li>
        {% endfor %}
      </ul>
{% endblock %}

django/templates/adminpanel.html
{% extends 'main.html' %}
{% block pagebody %}
    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            <h1 class="header center orange-text">Admin Panel</h1>
            <div class="row">
                <div class="item">
                    <h3>Scores</h3>
                    <p>Click the button to {{ showscorestate|yesno:"hide the scores.,show the scores.!"}}</p>
                    <form action="/adminpanel/" method="post">
                        {% csrf_token %}
                        {% if showscorestate %}
                            <input class="waves-effect wave-light btn red" type="submit" name="setshowscore" value="hide"></input>
                        {% else %}
                            <input class="waves-effect wave-light btn green" type="submit" name="setshowscore" value="show"></input>
                        {% endif %}
                    </form>
                </div>
                <div class="item-end">
                    <h3>Submissions</h3>
                    <p>Click the button to {{ submissionstate|yesno:"close the submissions.,open the submissions. Make sure you open the submissions at the correct time!"}}</p>
                    <form action="/adminpanel/" method="post">
                        {% csrf_token %}
                        {% if submissionstate %}
                            <input class="waves-effect wave-light btn red" type="submit" name="setsubmissions" value="close"></input>
                        {% else %}
                            <input class="waves-effect wave-light btn green" type="submit" name="setsubmissions" value="open"></input>
                        {% endif %}
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="item">
                    <h3>Add teams</h3>
                    <p>Since adding teams is quite a hassle to do in the admin interface, here you can automatically enter teams into the database by providing an enter-separated list of team names. A CSV file with the teams and tokens can be found on the server after you've generated the teams here. This is a file containing all the team names and passwords in plain text. We do not store this data in the database since Django doesn't allow it and it is not a good idea, this CSV is a workaround so you can still generate the teams and access all this data in a nice format. Ask the developer/administrator to get it from the server.</p>
                    <form action="/adminpanel/" method="post">
                        {% csrf_token %}
                        <textarea class="teaminput" id="teams" name="teams"></textarea>
                        <input class="waves-effect wave-light btn green" type="submit" name="addteams" value="submit"></input>
                    </form>
                </div>
                
                <div class="item-end">
                    <div>
                        <h3>Quick links</h3>
                        <p>
                            <a href="/adminrate" target="_blank">> Location and picture rating</a> <br>
                            <a href="/admintaskrate" target="_blank">> Regular and location tasks rating</a> <br>
                <a href="/admindownload" target="_blank">> Download all aftermovie images</a> <br>
                            <a href="/adminratedist" target="_blank">> Distributed rating</a> <br>
                            <a href="/admin/rially/bonus" target="_blank">> Add bonus points</a> <br>
                            <a href="/admin/rially/penalty" target="_blank">> Add penalty points</a>
                        </p>
                    </div>

                    <div>
                        <h3>To do before Rially:</h3>
                        > Add teams (on this page)<br>
                        > Send teams their password and telegram key (located in teams.csv on the server)<br>
                        <a href="/admin/rially/puzzle" target="_blank">> Add puzzles</a><br>
                        <a href="/admin/rially/location" target="_blank">> Add locations</a><br>
                        <a href="/admin/rially/task" target="_blank">> Add tasks</a><br>
                        <a href="/admin/rially/locationtask" target="_blank">> Add location tasks</a><br>
                        <a href="/admin/rially/picture" target="_blank">> Add bonus pictures</a><br>
                        > Open the submissions
                    </div>
                </div>
            </div>
            <div class="row">
            </div>

        </div>
    </div>


    <div class="container">
    </div>
{% endblock %}

django/templates/adminrate.html
{% extends 'main.html' %}
{% load static %}
{% block pagebody %}
    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            {% if page_type == "task" %}
                <h1 class="header center orange-text">Admin task rate</h1>
                <p class="center">This page is for rating tasks and location tasks (T-5, T-1-1)</p>
            {% elif page_type == "location" %}
                <h1 class="header center orange-text">Admin location rate</h1>
                <p class="center">This page is for rating locations and bonus pictures (L-2, PL-1-1)</p>
            {% endif %}
            <p class="center">{{ queue_length }} items in queue, {{ queue_important }} importants, longest wait time is {{ queue_longest|timesince }}.</p>
            <p class="center">
                <a href="/admin/rially/bonus/">Bonus points</a>
                <a href="/admin/rially/penalty/">Penalty points</a>
            </p>
            {% if messages %}
                <ul class="messages center">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
    <form id="frm" method="POST">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ id }}" />
        <input type="hidden" name="extra" id="extrafield" value="" />
        <input type="hidden" name="queue" value="{{ queue }}" />
        {% if type == 'task' or type == 'locationtask' %}
            <div class="container">
                <div class="row">
                    <div class="col s12 center">
                        <h4><b>{% if type == 'task' %}Task{% else %}Locationtask{% endif %}:</b> {{ subject.name }}</h4> <h6>By team {{ team }}</h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        {% include "media.html" with media=file %}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input placeholder="Points" id="points" name="points" type="number" class="validate" style="font-size:50px;text-align:center;">
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 center">
                        <p>
                            <input type="checkbox" id="aftermovie" name="aftermovie" />
                            <label for="aftermovie">This material must be in the aftermovie</label>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <a class="waves-effect waves-light btn" href="javascript:void(0);" onclick="check('Are you sure?');" style="width:100%;">Submit</a>
                    </div>
                </div>
            </div>
        {% elif type == 'location' %}
            <div class="container">
                <div class="row">
                    <div class="col s12 center">
                        <h4>Is the following location at <b>{{ subject.name }}</b>?</h4> <h6>By team {{ team }}</h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        {% include "media.html" with media=file %}
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 center">
                        <p>
                            <input type="checkbox" id="aftermovie" name="aftermovie" />
                            <label for="aftermovie">This material must be in the aftermovie</label>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s6">
                        <a class="waves-effect waves-light btn green" style="width:100%;" href="javascript:void(0);" onclick="check('Are you sure?','yes');">YES</a>
                    </div>
                    <div class="col s6">
                        <a class="waves-effect waves-light btn red" style="width:100%;" href="javascript:void(0);" onclick="check('Are you sure?','no');">NO</a>
                    </div>
                </div>
            </div>
        {% elif type == 'picture' %}
            <div class="container">
                <div class="row">
                    <div class="col s12 center">
                        <h4>Are the following pictures on the same location?</h4> <h6>By team {{ team }}</h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m6">
                        {% include "media.html" with media=subject_name %}
                    </div>
                    <div class="col s12 m6">
                        {% include "media.html" with media=file %}
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 center">
                        <p>
                            <input type="checkbox" id="aftermovie" name="aftermovie" />
                            <label for="aftermovie">This material must be in the aftermovie</label>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s6">
                        <a class="waves-effect waves-light btn green" style="width:100%;" href="javascript:void(0);" onclick="check('Are you sure?','yes');">YES</a>
                    </div>
                    <div class="col s6">
                        <a class="waves-effect waves-light btn red" style="width:100%;" href="javascript:void(0);" onclick="check('Are you sure?','no');">NO</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col s12 center">
                        <h4>The queue is empty or an error occurred. <BR>This page will be automatically refreshed in <b><span id="seconds">5</span></b> seconds.</h4>
                    </div>
                </div>
            </div>
        {% endif %}
    </form>
    <script>
        window.onload = function() {
            setTimeout(seconds, 1000);
        };
        function seconds() {
            var s = document.getElementById('seconds').innerText*1;
            if (s<=0) {
                // Set the location again because otherwise the user will send information multiple times
                // browsers will display a popup about this
                window.location=window.location;
                window.location.reload();
            } else {
                s--;
                document.getElementById('seconds').innerText = s;
                setTimeout(seconds, 1000);
            }
        }
        function check(txt, extra) {
            document.getElementById('extrafield').value = extra;
            if (confirm(txt)) {
                document.getElementById('frm').submit();
            }
        }
    </script>
{% endblock %}

django/templates/location.html
{% extends 'main.html' %}
{% block pagebody %}
    {% if location.pk in team.solved_locations %}
        <div class="section no-pad-bot" id="index-banner">
            <div class="container">
                <h1 class="header center orange-text">{{ object.name }}</h1>
                <div class="row center">
                    <h5 class="header col s12 light">{{ object.description }}</h5>
                </div>

            </div>
        </div>


        <div class="container">
            <div class="section">

                <!--   Icon Section   -->
                <div class="row">
                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center light-blue-text"><i class="material-icons">camera_alt</i></h2>
                            <h5 class="center">Bonus pictures</h5>
                            {% for picture in object.picture_set.all %}
                                <div class="row">
                                    <div class="col">
                                        <div class="card">
                                            <div class="card-image">
                                                <a href="{{ picture.image.url }}" target="_blank"><img src="{{ picture.image.url }}"{% if picture.pk in team.solved_pictures %} class="doneimage"{% endif %}></a>
                                                <!--
                                                {% if picture.pk in team.solved_pictures %}
                                                    <a class="btn-floating halfway-fab green"><i class="material-icons">done</i></a>
                                                {% else %}
                                                    <a class="btn-floating halfway-fab red"><i class="material-icons">close</i></a>
                                                {% endif %}
                                                -->
                                            </div>
                                            <div class="card-content">
                                                <p>
                                                    {% if picture.pk in team.solved_pictures %}
                                                        {% include 'code.html' with type='PL' location=location.id id=picture.id done=True processing=False%}
                                                    {% elif picture.pk in team.processing_pictures %}
                                                        {% include 'code.html' with type='PL' location=location.id id=picture.id done=False processing=True %}
                                                    {% else %}
                                                        {% include 'code.html' with type='PL' location=location.id id=picture.id done=False processing=False%}
                                                    {% endif %}
                                                    Bonus picture - {{ picture.points }} points</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center light-blue-text"><i class="material-icons">extension</i></h2>
                            <h5 class="center">Puzzles for the next location</h5>
                            <p class="center">
                            <ul class="collection with-header">
                                {% for puzzle in object.puzzle_set.all %}
                                    <li class="collection-item {% if nextlocation.id in team.solved_locations %}green lighten-4{% endif %}"><div>{{ puzzle.name }}{% if puzzle.file %}<a href="{{ puzzle.file.url }}" target="_blank" class="secondary-content"><i class="material-icons">attach_file</i></a>{% endif %}</div></li>
                                {% endfor %}
                            </ul>
                            {% if nextlocation %}
                                <div class="center">
                                    {% if nextlocation.id in team.solved_locations %}
                                        {% include 'code.html' with type='L' location=nextlocation.id done=True processing=False%}
                                    {% elif nextlocation.id in team.processing_locations %}
                                        {% include 'code.html' with type='L' location=nextlocation.id done=False processing=True %}
                                    {% else %}
                                        {% include 'code.html' with type='L' location=nextlocation.id done=False processing=False%}
                                    {% endif %}
                                </div>
                            {% endif %}
                            </p>

                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center light-blue-text"><i class="material-icons">assignment_late</i></h2>
                            <h5 class="center">Tasks</h5>

                            <p class="light">
                            <ul class="collection with-header">
                                {% for locationtask in object.locationtask_set.all %}
                                    <li class="collection-item {% if locationtask.pk in team.solved_locationtasks %}green{% elif locationtask.pk in team.processing_locationtasks %}orange{% endif %} lighten-4"><div>
                                        {% if locationtask.pk in team.solved_locationtasks %}
                                            {% include 'code.html' with type='TL' location=location.id id=locationtask.id done=True processing=False %}
                                        {% elif locationtask.pk in team.processing_locationtasks %}
                                            {% include 'code.html' with type='TL' location=location.id id=locationtask.id done=False processing=True %}
                                        {% else %}
                                            {% include 'code.html' with type='TL' location=location.id id=locationtask.id done=False processing=False %}
                                        {% endif %}
                                        {{ locationtask.name }}<!--<i class="material-icons secondary-content">{% if locationtask.pk in team.solved_locationtasks %}done{% else %}close{% endif %}</i>--></div>
                                    </li>
                                {% endfor %}
                            </ul>
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    {% else %}
        <div class="section no-pad-bot" id="index-banner">
            <div class="container">
                <h1 class="header center orange-text">???</h1>
                <div class="row center">
                    <h5 class="header col s12 light">You did not unlock this location yet.</h5>
                </div>

            </div>
        </div>


        <div class="container">
            <div class="section">

                <!--   Icon Section   -->
                <div class="row">
                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center light-blue-text"><i class="material-icons">camera_alt</i></h2>
                            <h5 class="center">Bonus pictures</h5>
                            <p class="center"><i class="material-icons" style="font-size:160px;color:#AAA;">lock</i></p>
                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center light-blue-text"><i class="material-icons">extension</i></h2>
                            <h5 class="center">Puzzles for the next location</h5>
                            <p class="center"><i class="material-icons" style="font-size:160px;color:#AAA;">lock</i></p>

                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center light-blue-text"><i class="material-icons">assignment_late</i></h2>
                            <h5 class="center">Tasks</h5>
                            <p class="center"><i class="material-icons" style="font-size:160px;color:#AAA;">lock</i></p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    {% endif %}
{% endblock %}

django/templates/media.html
{% if media|slice:"-4:" == ".mp4" %}
    <video style="width:100%;" controls>
        <source src="{{ media }}" type="video/mp4">
    </video>
{% else %}
    <a href="{{ media }}">
        <img src="{{ media }}" style="width:100%;"/>
    </a>
{% endif %}